<?php

use Fintoc\Payment\Block\Checkout\Success;
use Magento\Framework\Escaper;
/** @var Success $block */
/** @var Escaper $escaper */

$rows = $block->getRows();
if (!$rows) {
    return;
}
?>
<div class="fintoc-payment-info" data-bind="scope: 'fintoc-payment-info'">
    <div class="checkout-success-fintoc-title">
        <strong><?= /* @var Escaper $escaper */ $escaper->escapeHtml(__('Payment Information')); ?></strong>
    </div>
    <table class="data table fintoc-payment-table">
        <tbody>
        <?php foreach ($rows as $label => $value): ?>
            <tr>
                <th scope="row"><?= $escaper->escapeHtml((string)$label); ?></th>
                <td><?= /** @noEscape */ $value; ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>
<script>
    require(['Magento_Customer/js/customer-data'], function (customerData) {
        customerData.invalidate(['cart']);
        customerData.reload(['cart'], true);
    });
</script>
